# Generated by Django 5.2.8 on 2026-01-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=100)),
                ('service_price', models.FloatField()),
                ('service_Description', models.TextField()),
                ('service_image', models.ImageField(upload_to='')),
                ('service_quantity', models.IntegerField()),
            ],
        ),
    ]
