# Generated by Django 5.2.8 on 2026-02-07 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_website_xd_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_title',
            new_name='title',
        ),
    ]
