# Generated by Django 5.2.8 on 2026-02-21 08:10

import design_website_xd_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_website_xd_app', '0002_rename_service_description_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to=design_website_xd_app.models.Service.user_directory_path),
        ),
    ]
