# Generated by Django 5.2.8 on 2026-02-21 08:11

import design_website_xd_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_website_xd_app', '0003_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image2',
            field=models.ImageField(default='none', upload_to=design_website_xd_app.models.Service.user_directory_path),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='none', upload_to=design_website_xd_app.models.Service.user_directory_path),
        ),
    ]
